### ISSUE TITLE
Fehler in VIS Darstellung

### ISSUE THREAD

**Issue by matze939939** [Pix---/vis_widget_dwd_pollenflug#2]
Guten Tag,

ich habe nach Import des Widgets und dem CSS im VIS Editor die Daten dargestellt. Die eigentliche VIS zeigt jedoch nur leere Felder? Woran kann dies liegen?

Vielen Dank für jeden Denkanstoß!

 
![Ansicht_Editor_VIS_VIS](https://user-images.githubusercontent.com/58843894/80864760-f3ad1600-8c84-11ea-9225-adb681b4f67a.png)

**Comment by Pix---** [comment]
Hallo,
hast du den Regional-Code im Widget durch deinen ersetzt? Im Widget ist per Standard #121 (Oberbayern) eingestellt. Vor dem Import nach VIS solltest du "#121" gegen die in deinem  Pollenflug-Adapter eingestellte Region ersetzen.

Siehe auch hier [ioBroker Forum](https://forum.iobroker.net/user/knusterus)

**Comment by matze939939** [comment]
Hallo,

ja, dass habe ich und dann den geänderten Widget Code in der VIS eingesetzt. Im VIS Editor bekomme ich das Widget ja auch korrekt angezeigt. In der eigentlichen VIS dann jedoch nicht.
Heute stelle ich fest, dass der CSS Code nicht mehr vorhanden / gespeichert ist. Kann mein Problem ggf. damit zu tun haben? Muss dieser noch separat im Projekt gespeichert werden?

**Comment by Pix---** [comment]
Ja, die CSS Befehle müssen in VIS im Reiter Projekt abgelegt werden.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by matze939939** [comment]
Vielen Dank. Das Problem lag in meiner VIS. Nach Ex- und Reimport dieser funktioniert alles perfekt.
